---
- name: Deploy InfluxDB Docker Container
  hosts:
    docker
  vars_files:
    - env
  become: true
  become_user: "{{ ansible_user }}"
  vars_prompt:
  - name: username
    prompt: Enter InfluxDB username
    private: no
    default: scriber
  - name: password
    prompt: Enter InfluxDB user password
    default: scriberpass
  - name: org
    prompt: Enter InfluxDB organization name
    default: seacreeper
  - name: bucket
    prompt: Enter InfluxDB default bucket name
    default: scribes
  tasks:
    - name: Copy Docker Compose YAML
      copy:
        src: requirements
        dest: "{{ directory }}"
    - name:  Deploy InfluxDB
      command: docker-compose -p db up -d
      args:
        chdir: "{{ directory }}/requirements"
      environment:
        INFLUXDB_USERNAME: "{{ username }}"
        INFLUXDB_PASSWORD: "{{ password }}"
        INFLUXDB_ORG: "{{ org }}"
        INFLUXDB_BUCKET: "{{ bucket }}"
    - name: Delete Docker Compose YAML
      file:
        state: absent
        path: "{{ directory }}"
